### ISSUE TITLE
Preserve contentMode and "show resources" during navigation

### ISSUE THREAD

**Issue by chegoryu** [ytsaurus/ytsaurus-ui#511]
I use `contentMode=resources` and `show resources` to find "bad" directories with high quota usage.

<img width="2285" alt="Screenshot 2024-04-23 at 13 50 10" src="https://github.com/ytsaurus/ytsaurus-ui/assets/29466571/82747ae1-71fe-48a3-bf48-7acd38f6854b">

However sometimes you need to go into some subdirectories to find exact bad directory/table without merged chunks/etc.

But right now after clicking on subdirectory `contentMode=resources` and `show resources` options are reset, so you need to enable them again and it is really inconvenient.

**Comment by chegoryu** [comment]
> But show the resources button are reset on purpose as it could be heavy on the back-end side to rerun it again at a big clusters.

Okay...

Anyway thanks for contentMode fix :)

**Comment by vrozaev** [comment]
The root cause of contentMode problem might be somewhere here: https://github.com/ytsaurus/ytsaurus-ui/blob/bf64b2cf9aef5e5d6281799e45c831eb58f910f3/packages/ui/src/ui/store/reducers/navigation/content/map-node/url-mapping.ts#L36.

Here `draftMapNode.contentMode === 'resources'` and `queryMapNode.contentMode === 'default'`. So far it's not clear why it's done this way. This code is a part of [navigation url-mapping module](https://github.com/ytsaurus/ytsaurus-ui/blob/bf64b2cf9aef5e5d6281799e45c831eb58f910f3/packages/ui/src/ui/store/reducers/navigation/url-mapping.ts#L89) which a bit obscure.

**Comment by vrozaev** [comment]
Done, now we do not reset contentMode between pages.
