### ISSUE TITLE
Navigation that is hidden under ... don't work for getting back to home or other directories

### ISSUE THREAD

**Issue by rBunin** [ytsaurus/ytsaurus-ui#528]
![image](https://github.com/ytsaurus/ytsaurus-ui/assets/11693270/22cc853c-5cdf-4914-bd62-cd81c62de002)

**Comment by SimbiozizV** [comment]
The problem should be resolved after completing this task https://github.com/ytsaurus/ytsaurus-ui/issues/502

**Comment by vrozaev** [comment]
In YT we render all breadcrumbs elements as links, and ignore `action()` callback.

So the rootcase of the problems is that [Breadcrumbs](https://preview.gravity-ui.com/uikit/?path=/docs/components-navigation-breadcrumbs--docs) component didn't allow us to render custom content in that dropdown. Dropdown elements rely on action which are doing nothing in our case.

As I see, the right way to solve this problem is support custom render for breadcrumbs dropdown.

**Comment by vrozaev** [comment]
I decided to rewrite yt code in order to use `action()` callback, because that solution much easy to do right now.

In future we can extend the Breadcrumbs component if we want so.

**Comment by vrozaev** [comment]
NB: current Breadcrumbs component should be removed in next major release of uikit, so there are no need to patch this component right now.

The new component is here: https://preview.gravity-ui.com/uikit/?path=/docs/lab-breadcrumbs--docs, so far it is unstable.
